Switched from folders to submodules
Note: while commiting, error on GitHub Desktop:
Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.13
OS: Mac OS 10.13.2